amqp:
  queue: myQueue
spring:
  datasource:
    url: jdbc:h2:~/fiapbatchcontrol;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: <smtp email address>
    password: <smtp email password>
    port: 587
    subject: Dados de coleta Drone
    to: <receiver email>
    from: <smtp email address>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
